// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function range(x, y) {
  var match = +(x >= y);
  if (match !== 0) {
    return /* [] */0;
  } else {
    return /* :: */[
            x,
            range(x + 1 | 0, y)
          ];
  }
}

function factorsOfNumber(max) {
  return List.filter((function (number) {
                  return +(Caml_int32.mod_(max, number) === 0);
                }))(range(1, max + 1 | 0));
}

var Utils = /* module */[
  /* range */range,
  /* factorsOfNumber */factorsOfNumber
];

exports.Utils = Utils;
/* No side effect */
