// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List              = require("bs-platform/lib/js/list.js");
var Pervasives        = require("bs-platform/lib/js/pervasives.js");
var Exercism$Exercism = require("./Exercism.bs.js");

function raindrops(number) {
  var factors = Exercism$Exercism.Utils[/* factorsOfNumber */1](number);
  var raindropSpeak = "";
  if (List.mem(3, factors)) {
    raindropSpeak = raindropSpeak + "Pling";
  }
  if (List.mem(5, factors)) {
    raindropSpeak = raindropSpeak + "Plang";
  }
  if (List.mem(7, factors)) {
    raindropSpeak = raindropSpeak + "Plong";
  }
  var match = +(raindropSpeak === "");
  if (match !== 0) {
    return Pervasives.string_of_int(number);
  } else {
    return raindropSpeak;
  }
}

console.log("the sound for 1 is 1");

var match = +(raindrops(1) === "1");

console.log(match !== 0 ? "Passed" : "Failed");

console.log("the sound for 3 is Pling");

var match$1 = +(raindrops(3) === "Pling");

console.log(match$1 !== 0 ? "Passed" : "Failed");

console.log("the sound for 15 is PlingPlang as it has factors 3 and 5");

var match$2 = +(raindrops(15) === "PlingPlang");

console.log(match$2 !== 0 ? "Passed" : "Failed");

console.log("the sound for 35 is PlangPlong as it has factors 5 and 7");

var match$3 = +(raindrops(35) === "PlangPlong");

console.log(match$3 !== 0 ? "Passed" : "Failed");

console.log("the sound for 105 is PlingPlangPlong as it has factors 3, 5 and 7");

var match$4 = +(raindrops(105) === "PlingPlangPlong");

console.log(match$4 !== 0 ? "Passed" : "Failed");

console.log("the sound for 3125 is Plang as it has a factor 5");

var match$5 = +(raindrops(3125) === "Plang");

console.log(match$5 !== 0 ? "Passed" : "Failed");

exports.raindrops = raindrops;
/*  Not a pure module */
